---
title: "da-ws-10-1"
author: "Charlotte Gohr, Marvin Ludwig, Klaas Rueggeberg"
date: "16 Januar 2017"
output: html_document
---

## Precipitation forecast
```{r, include = FALSE}
library(forecast)
```

```{r}
# initialise script
source("d:/university/msc-phygeo-class-of-2016-Ludwigm6/fun/init.R")
path <-  fun_init("da", "10")

# read data
data <- read.table(paste0(path$da$csv, "produkt_synop_Terminwerte_20060701_20151231_03164.txt"), sep = ";", header = TRUE)

# create new column with the first 6 digits of MESS_DATUM (year and month)
data$agg <- substr(data$MESS_DATUM, 1, 6)

# aggregate the monthly precipitation 
prec <- aggregate(data$NIEDERSCHLAGSHOEHE, by = list(data$agg), FUN = sum)
names(prec) <- c("date", "prec")

# divide data in test (last 2 years) and train (rest)
train <- prec[prec$date < 201401,]
test <- prec[prec$date >= 201401,]

# create data frame with all possible parameter combinations
parameters <- expand.grid(p = seq(0,5), d = seq(0,2), q = seq(0, 5), ps = seq(0, 2), ds = seq(0, 2), qs = seq(0, 2))

```

```{r, eval = FALSE}
# # # arima model with all parameter combinations # # #
res <- lapply(seq(nrow(parameters)), function(x){
  mod <- arima(train$prec,
               order = c(parameters$p[x], parameters$d[x], parameters$q[x]),
               seasonal = list(order = c(parameters$ps[x], parameters$ds[x], parameters$qs[x])),
               method = "ML")
  pre <- predict(mod, n.ahead = 24)
  
  return(data.frame(p = parameters$p[x], d = parameters$d[x], q = parameters$q[x],
                    ps = parameters$ps[x], ds = parameters$ds[x], qs = parameters$qs[x],
                    rmse = sqrt(mean((pre$pred - test$prec)^2))))
})
# save results
saveRDS(res, file = paste0(path$da$RData, "precipitation_model.RDS"))
# # #
```

```{r}
# load results to save computation time
res <- readRDS(paste0(path$da$RData, "precipitation_model.RDS"))
res <- do.call("rbind", res)

# best model is the one with the smallest rmse
best_par <- res[min(res$rmse),]
# get the model and prediction with the best parameters
best_mod <- arima(train$prec,
                  order = c(best_par$p,best_par$d,best_par$q),
                  seasonal = list(order = c(best_par$ps, best_par$ds, best_par$qs)),
                  method = "ML")
best_pred <- predict(best_mod, n.ahead = 24)

# auto arima
ts_prec <- ts(train$prec, start = c(2006, 7), end = c(2013, 12), frequency = 12)
auto_mod <- forecast::auto.arima(ts_prec, max.p = 5, max.d = 2, max.q = 5, stationary = TRUE, seasonal = TRUE)


# compare auto-arima and best model
# stats of best model:
best_par$AIC <- best_mod$aic
auto_stats <- data.frame(p = 2, d = 0, q = 2, ps = NA, ds = NA, qs = NA, rmse = summary(auto_mod)[2], AIC = auto_mod$aic)
model_stats <- rbind(best_par, auto_stats)
rownames(model_stats) <- c("arima", "auto_arima")

print(model_stats)

# # # plot results
# best_mod
# convert results into time series to get a nice x-axis
prec_ts <- ts(prec$prec, start = c(2006, 7), end = c(2015, 12), frequency = 12)
pred_ts <- ts(best_pred$pred, start = c(2014, 1), end = c(2015, 12), frequency = 12)
pred_se <- ts(best_pred$se, start = c(2014, 1), end = c(2015, 12), frequency = 12)

plot(prec_ts, main = "Arima (3,1,1)(0,0,0)", ylab = "Precipitation")
lines(pred_ts, col = "red")
lines(pred_ts+pred_se, col = "blue")
lines(pred_ts-pred_se, col = "blue")

# auto arima
plot(forecast(auto_mod), main = "Auto Arima (2,0,2)", ylab  = "Precipitation")


```

