---
title: "rs-ws-06-2"
author: "Charlotte Gohr, Marvin Ludwig, Klaas Rueggeberg"
date: "21 Dezember 2016"
output: html_document
---

## Training and Test
```{r, eval = FALSE}
source("d:/university/msc-phygeo-class-of-2016-Ludwigm6/fun/init.R")
path <- fun_init("rs", "06")
path$samples <- paste0(path$rs$run, "samples/")


library(caret)
library(rgdal)
library(raster)

# load training sites 
train_sites <- readOGR(paste0(path$rs$run, "training_sites.shp"))

# write each polygon in a list
separate <- lapply(seq(length(train_sites)), function(i) train_sites[i,])

# get 80 % of the index numbers (6 times)
sites_sample <- createDataPartition(train_sites@data$ID, p = 0.80, list = FALSE, times = 6)


# samples is a list with 6 entries. each entry contains two spatialpolygondataframes: train and test
samples <- lapply(seq(ncol(sites_sample)), function(x){
  
  # get 80% of the polygons based on the numbers in sites_sample
  train <- lapply(sites_sample[,x], function(i) rbind(separate[[i]]))
  train <- do.call("rbind", train)
  
  # get the remaining 20%
  test <- lapply(seq(length(train_sites))[-sites_sample[,x]], function(j) rbind(separate[[j]]))
  test <- do.call("rbind", test)  
  
  return(list(train = train, test = test))
  
})

# create output folder
dir.create(paste0(path$samples))

# save each list entry as shapefile 
for(k in seq(6)){
  writeOGR(samples[[k]]$train, dsn = paste0(path$sample, "train_", as.character(k), ".shp"), driver = "ESRI Shapefile", layer = "train")
  writeOGR(samples[[k]]$test, dsn = paste0(path$sample, "test_", as.character(k), ".shp"), driver = "ESRI Shapefile", layer = "test")
}


```
#### Here is where some QGIS and OTB happens


## Compute Kappa
```{r}

source("d:/university/msc-phygeo-class-of-2016-Ludwigm6/fun/init.R")

path <- fun_init("rs", "06")
path$samples <- paste0(path$rs$run, "samples/")
source(path$fun$fun_compKappa.R)


matrix_files <- list.files(path$samples, pattern = "*.csv", full.names = TRUE)

kappa <- lapply(seq(length(matrix_files)), function(x){
  
  # load matrix and extract rows and cols
  m <- read.csv(matrix_files[[x]], skip = 0, header = FALSE)
  rows <- unlist(m[1,])
  cols <- unlist(m[2,])
  
  # load matrix again; skip the row index and with cols as header
  m <- read.csv(matrix_files[[x]], skip = 1, header = TRUE)
  
  
  # make the matrix a square
  template <- matrix(nrow = 40, ncol = 40, data = 0)
  for(i in seq(40)){
    for(j in seq(40)){
      if(i %in% rows & j %in% cols){
        template[i,j] <- m[which(rows == i), which(cols == j)]
      }
    }
  }
  
  return(compKappa(ctable = template))

})

print(kappa)

```